<a href="https://colab.research.google.com/github/fernandacisneross/unidad1/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

numpy es una libreria de python.
numpy se utiliza para trabajar con matrices o arreglos.
numpy es la abreviatura de "python numerico"
tambien tiene funciones para trabajar en el dominio del algebra lineal,la transformada y las matrices
en python tenemos listas que sirven como matrices pero son lentas de procesar.numpy tiene como objetivo proporcionar un objeto de matriz que sea 50 veces mas rapido que las listas tradicionales.

In [ ]:
#primero tenemos que importar la libreria
import numpy

arreglo=numpy.array([12345])
print(arreglo)

[12345]


numpy como np
numpy generalmente se importa bajo el alias np.en python los alias son un nombre alternativo para referirse a la misma cosa

In [ ]:
import numpy as np

arreglo=np.array([6,7,8,9])
print(arreglo)

[6 7 8 9]


comprobando la version de numpy la cadena de la version se almacena en el atributo__version__

In [ ]:
import numpy as np

print(np.__version__)

2.0.2


numpy creando matrices
crear un objeto ndarray de numpy
numpy se utiliza para trabajar con matrices.el objeto de matriz se llama ndarray.
podemos crear un numpy ndarray utilizando la funcion array()

In [ ]:
import numpy as np
arreglo=np.array(["raul","ana","kimberly","yazmin"])
print(arreglo)
print(type(arreglo))

['raul' 'ana' 'kimberly' 'yazmin']
<class 'numpy.ndarray'>


dimensiones en matrices
una dimension en matrices es un nivel de profundidad de matriz(matrices anidadas)
una matriz anidada contiene matrices como elementos
matrices 0-D.son elementos de una matriz.cada valor de una matriz es una matriz 0-D.ejemplo:crea una matriz 0-D con un valor de 42

In [ ]:
import numpy as np

arreglo=np.array(42)
print(arreglo)

42


matrices 1-D
una matriz que tiene matrices 0-D como elementos se denomina matriz unidimensional o 1-D.
estas son las matrices mas comunes y basicas.
ejemplo:crea una matriz de 1-D que tenga los valores 1,2,3,4,5

In [ ]:
import numpy as np

arreglo=np.array([1,2,3,4,5])

print(arreglo)

[1 2 3 4 5]


matrices 2-D
una matriz que tiene como matrices 1-D como elementos se denomina 2-D.
a menudo se utilizan para representar mareices de segundo orden.numpy tiene un submodulo completo dedicado a operaciones con matrices llamado numpy.mat.
ejemplo:crea una matriz 2D que con tenga dos matrices con los valores 123 y 456.

In [ ]:
import numpy as np
arreglo=np.array([[1,2,3],[4,5,6]])

print(arreglo)

[[1 2 3]
 [4 5 6]]


matrices 3D
una matriz que tiene matrices 2D se denomina 3D.
estas matrices se utilizan para representar una matriz de tercer orden.
ejemplo:crea una matriz 3D con dos matrices bidimencionales,ambas conteniendo dos matrices con los valores 123 y 456.

In [ ]:
import numpy as np
arreglo=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arreglo)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
