<a href="https://colab.research.google.com/github/fernandacisneross/unidad1/blob/main/practica6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
fernanda estrella cisneros castañeda-24 de septiembre de 2025-practica6-cortar arreglos numpy
---------------------------
slice en python significa tomar elementos de un indice determinado indice
---------------------------
pasamos slice en lugar del indice de esta manera:[started]sino pasamos el inicio se considera o si no pasamos el final,su longitud se considera una matriz de una dimension
ejemplo:([1,2,3,4,5,6,7]) cortamos los elementos del indice 1 al indice 5

In [2]:
import numpy as np
arreglo=np.array([1,2,3,4,5,6,7])
print(arreglo[1:5])

[2 3 4 5]


ejemplo2:([1,2,3,4,5,6,7]) cortar del indice 4 hasta el final de la matriz

In [4]:
import numpy as np
arreglo=np.array([1,2,3,4,5,6,7])
print(arreglo[4:])


[5 6 7]


ejemplo3:([1,2,3,4,5,6,7]) cortar elementos desde el principio hasta el indice 5

In [5]:
import numpy as np
arreglo=np.array([1,2,3,4,5,6,7])
print(arreglo[:5])

[1 2 3 4 5]


ejemplo 4:([1,2,3,4,5,6,7])
corte negativo .utilizamos el operador W-" para hacer referencia a un indice desde el final.
----------------
cortar del indice 3 desde el final al indice 1 desde el final

In [6]:
import numpy as np
arreglo=np.array([1,2,3,4,5,6,7])
print(arreglo[-3:-1])

[5 6]
